// Bakes the home page globe's land dots into src/components/site/home/land-dots.ts, so the browser doesn't have to
// download a world map and work out which dots are on land every time the page loads. Run with: npm run globe
//
// The globe's dots sit on a Fibonacci lattice (evenly spread over the sphere, numbered from the north pole down), so a
// dot is fully described by its number and the browser can recompute where it is. All we ship is what each dot is:
// 2 bits each (0 sea, 1 land, 2 India, 3 Australia), packed four to a byte, deflated, then base64 so it can live in a
// module. The globe decodes it with the browser's own DecompressionStream. Two lattices: a finer one for big screens,
// a coarser one for phones.
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { feature } from "topojson-client";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const home = path.join(root, "src/components/site/home");
const LATTICES = [30000, 60000];

const land = JSON.parse(fs.readFileSync(path.join(root, "node_modules/world-atlas/land-110m.json"), "utf8"));
const outlines = JSON.parse(fs.readFileSync(path.join(home, "outlines.json"), "utf8"));

const geo = feature(land, land.objects.land).features[0].geometry;
const rings = (geo.type === "Polygon" ? [geo.coordinates] : geo.coordinates).flat().map((ring) => {
  const lons = ring.map((p) => p[0]);
  const lats = ring.map((p) => p[1]);
  return { ring, box: [Math.min(...lons), Math.max(...lons), Math.min(...lats), Math.max(...lats)] };
});

function inside([x, y], poly) {
  let hit = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i];
    const [xj, yj] = poly[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) hit = !hit;
  }
  return hit;
}

// Even-odd across every ring, so lakes and inland seas stay holes.
function isLand(ll) {
  let hit = false;
  for (const { ring, box } of rings) {
    if (ll[0] >= box[0] && ll[0] <= box[1] && ll[1] >= box[2] && ll[1] <= box[3] && inside(ll, ring)) hit = !hit;
  }
  return hit;
}

/** Must match the lattice in globe-scene.ts. */
function lonLat(i, n) {
  const golden = Math.PI * (3 - Math.sqrt(5));
  const y = 1 - ((i + 0.5) / n) * 2;
  const r = Math.sqrt(1 - y * y);
  const [x, z] = [Math.cos(i * golden) * r, Math.sin(i * golden) * r];
  return [(Math.atan2(-z, x) * 180) / Math.PI, (Math.asin(y) * 180) / Math.PI];
}

const encoded = {};
for (const n of LATTICES) {
  const packed = new Uint8Array(Math.ceil(n / 4));
  const tally = [0, 0, 0, 0];
  for (let i = 0; i < n; i++) {
    const ll = lonLat(i, n);
    const kind = !isLand(ll) ? 0 : inside(ll, outlines.india) ? 2 : inside(ll, outlines.australia) ? 3 : 1;
    packed[i >> 2] |= kind << ((i & 3) * 2);
    tally[kind]++;
  }
  const deflated = zlib.deflateRawSync(packed, { level: 9 });
  encoded[n] = deflated.toString("base64");
  console.log(`${n} dots: ${tally[1] + tally[2] + tally[3]} on land (${tally[2]} India, ${tally[3]} Australia), ${packed.length} bytes packed, ${deflated.length} deflated`);
}

const out = `// Generated by scripts/build-globe.mjs from world-atlas land-110m and outlines.json. Do not edit; run npm run globe.
// What each dot of the globe's Fibonacci lattice is (0 sea, 1 land, 2 India, 3 Australia), 2 bits per dot, deflated,
// base64. Keyed by the lattice's size.
export const LAND_DOTS: Record<number, string> = {
${LATTICES.map((n) => `  ${n}: "${encoded[n]}",`).join("\n")}
};
`;
fs.writeFileSync(path.join(home, "land-dots.ts"), out);
console.log(`Wrote src/components/site/home/land-dots.ts (${out.length} bytes)`);
